name: fluorflow_generator
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.0.6

dependencies:
  analyzer:
  build:
  code_builder:
  dart_style:
  fluorflow:
    git:
      url: git@github.com:smartive/fluorflow.git
      ref: main
  glob:
  path:
  source_gen:

dev_dependencies:
  build_test:
  lints:
  test:
# dependency_overrides:
#   fluorflow:
#     path: ../fluorflow
