name: fluorflow_generator
description: A starting point for Dart libraries or applications.
version: 0.0.0-development
publish_to: none

environment:
  sdk: ^3.0.6

dependencies:
  analyzer:
  build:
  code_builder:
  dart_style:
  fluorflow:
    # path: ../fluorflow
    git:
      url: https://github.com/smartive/fluorflow.git
      ref: main
  glob:
  path:
  recase:
  source_gen:

dev_dependencies:
  build_test:
  lints:
  mockito:
  test:
