name: fluorflow_generator
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.0.6

dependencies:
  analyzer: ^6.0.0
  build: ^2.4.1
  code_builder: ^4.5.0
  dart_style: ^2.3.2
  fluorflow:
    path: ../fluorflow
    # git:
    #   url: git@github.com:smartive/fluorflow.git
    #   ref: main
  glob: ^2.1.2
  path: ^1.8.3
  recase: ^4.1.0
  source_gen: ^1.4.0

dev_dependencies:
  build_test:
  lints:
  test:
